// Command fontgen は UI で使う文字だけを bitmapfont/v4（FaceEA）からラスタライズし、
// グリフアトラス PNG と対応表（Go ソース）を生成する。
//
//	go run ./tools/fontgen -src internal/ui -out internal/uifont
//
// bitmapfont を実行時に埋め込むと 6 言語分（約 2.7MB）が wasm に含まれるため、
// ビルド時にアトラス化してサイズを抑える。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"
	"path/filepath"

	"github.com/hajimehoshi/bitmapfont/v4"
	"golang.org/x/image/font"
	"golang.org/x/image/math/fixed"

	"github.com/nasuton/Solitaire/internal/fontscan"
)

const columns = 32

func main() {
	src := flag.String("src", filepath.Join("internal", "ui"), "文字列リテラルを走査する Go パッケージのディレクトリ")
	out := flag.String("out", filepath.Join("internal", "uifont"), "atlas.png と glyphs_gen.go の出力先")
	flag.Parse()
	if err := run(*src, *out); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run(srcDir, outDir string) error {
	extra, err := fontscan.Runes(srcDir)
	if err != nil {
		return err
	}
	runes := append(fontscan.ASCII(), extra...)
	// 欠落文字の代替として U+FFFD（置換文字）があれば含める。
	runes = append(runes, '\uFFFD')

	face := bitmapfont.FaceEA
	m := face.Metrics()
	cellH := m.Height.Ceil()
	ascent := m.Ascent.Ceil()
	cellW := 0
	type glyph struct {
		r   rune
		adv int
	}
	var glyphs []glyph
	for _, r := range runes {
		adv, ok := face.GlyphAdvance(r)
		if !ok {
			return fmt.Errorf("U+%04X %q はフォントに存在しません", r, string(r))
		}
		a := adv.Ceil()
		if a > cellW {
			cellW = a
		}
		glyphs = append(glyphs, glyph{r: r, adv: a})
	}

	rows := (len(glyphs) + columns - 1) / columns
	img := image.NewRGBA(image.Rect(0, 0, columns*cellW, rows*cellH))
	draw.Draw(img, img.Bounds(), image.Transparent, image.Point{}, draw.Src)
	d := &font.Drawer{Dst: img, Src: image.NewUniform(color.White), Face: face}
	for i, g := range glyphs {
		cx := (i % columns) * cellW
		cy := (i / columns) * cellH
		d.Dot = fixed.P(cx, cy+ascent)
		d.DrawString(string(g.r))
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	var pngBuf bytes.Buffer
	enc := png.Encoder{CompressionLevel: png.BestCompression}
	if err := enc.Encode(&pngBuf, img); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "atlas.png"), pngBuf.Bytes(), 0o644); err != nil {
		return err
	}

	var src bytes.Buffer
	fmt.Fprintf(&src, "// Code generated by tools/fontgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&src, "package uifont\n\n")
	fmt.Fprintf(&src, "const (\n\tcellW = %d\n\tcellH = %d\n\tascent = %d\n\tcolumns = %d\n)\n\n", cellW, cellH, ascent, columns)
	fmt.Fprintf(&src, "// glyphs は rune → アトラス内インデックスと送り幅。\n")
	fmt.Fprintf(&src, "var glyphs = map[rune]glyph{\n")
	for i, g := range glyphs {
		fmt.Fprintf(&src, "\t0x%04X: {%d, %d}, // %q\n", g.r, i, g.adv, string(g.r))
	}
	fmt.Fprintf(&src, "}\n")
	formatted, err := format.Source(src.Bytes())
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "glyphs_gen.go"), formatted, 0o644); err != nil {
		return err
	}
	fmt.Printf("%d glyphs, atlas %dx%d, png %d bytes\n", len(glyphs), img.Bounds().Dx(), img.Bounds().Dy(), pngBuf.Len())
	return nil
}
